import os  

# Set APIkey for Azure OpenAI Service
API_TYPE = os.environ.get('API_TYPE')
AZURE_OPENAI_API_KEY = os.environ.get('AZURE_OPENAI_API_KEY')
AZURE_OPENAI_ENDPOINT = os.environ.get('AZURE_OPENAI_ENDPOINT')
AZURE_OPENAI_API_VERSION = os.environ.get('AZURE_OPENAI_API_VERSION')
CHAT_MODEL = os.environ.get('CHAT_MODEL')
CHAT_COMPLETION_MODEL = os.environ.get('CHAT_COMPLETION_MODEL')
EMBEDDING_MODEL = os.environ.get('EMBEDDING_MODEL')
EMBEDDING_MODEL_TYPE = os.environ.get('EMBEDDING_MODEL_TYPE')

# YOUR_AZURE_SEARCH_ENDPOINT
AZURE_SEARCH_SERVICE_ENDPOINT = os.environ.get('AZURE_SEARCH_SERVICE_ENDPOINT')
# YOUR_AZURE_SEARCH_ADMIN_KEY
AZURE_SEARCH_API_KEY = os.environ.get('AZURE_SEARCH_API_KEY')

Login = os.environ.get('Login')